version: '2'
services:
  web:
    image: rochdev/maclev-web:latest
    links:
      - postgres
    ports:
      - 80:80
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  postgres:
    image: postgres:9
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
