version: '2'
services:
  web:
    build: ./maclev-web
    command: ./node_modules/.bin/gulp
    volumes:
      - ./maclev-web/src:/usr/src/app/src
    ports:
      - 80:80
    links:
      - proxy
  proxy:
    build: ./maclev-proxy
  api:
    build: ./maclev-api
    command: nodemon -L .
    volumes:
      - ./maclev-api/lib:/usr/src/app/lib
      - ./maclev-api/test:/usr/src/app/test
      - ./maclev-api/migrations:/usr/src/app/migrations
  scheduler:
    build: ./maclev-scheduler
    command: nodemon -L .
    volumes:
      - ./maclev-scheduler/index.js:/usr/src/app/index.js
  postgres:
    ports:
      - 5432:5432
  queue-ui:
    build: ./maclev-queue-ui
    environment:
      - REDIS_URL=redis://queue:6379
