version: '2'
services:
  api:
    image: rochdev/maclev-api:latest
    links:
      - postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  postgres:
    image: postgres:9
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
