version: '2'
services:
  proxy:
    image: rochdev/maclev-proxy:latest
    links:
      - api
      - queue-ui
    restart: always
  api:
    image: rochdev/maclev-api:latest
    links:
      - postgres
    restart: always
  scheduler:
    image: rochdev/maclev-scheduler:latest
    links:
      - queue
    restart: always
  postgres:
    image: postgres:9
    restart: always
  queue:
    image: redis:3-alpine
    restart: always
  queue-ui:
    image: rochdev/maclev-queue-ui
    links:
      - queue
    restart: always
